import Header from '@/components/Header';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const ErrorButton = dynamic(() => import('@/components/ErrorButton'), {
  ssr: false,
});

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Harry Potter Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/favicon.ico" />
      </Head>
      <Header />
      Hello
      <ErrorButton />
    </>
  );
}

export async function getServerSideProps() {
  const response = await fetch(
    'https://api.potterdb.com//v1/characters?page[size]=10&page[number]=1'
  );
  const data = await response.json();
  return {
    props: {
      characters: data,
    },
  };
}
