// import { getCharacters } from '@/api/getItems';
import Header from '@/components/Header';
import Main from '@/components/Main';
import { getCharacters, reduxApi } from '@/store/api/characterApi';
import { wrapper } from '@/store/store';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const ErrorButton = dynamic(() => import('@/components/ErrorButton'), {
  ssr: false,
});

export default function HomePage(data) {
  // console.log(data);
  const charactersData = data.cards.data.data;
  // console.log(charactersData);
  return (
    <>
      <Head>
        <title>Harry Potter Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/favicon.ico" />
      </Head>
      <Header />
      {/* {JSON.stringify(data)} */}
      {/* Hello */}
      <Main
        className={charactersData.length ? 'fullwidth' : 'width2/3'}
        items={charactersData}
        count={data.cards.data.meta.pagination.records}
        // onPageChange={() => {}}
      />
      <ErrorButton />
    </>
  );
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (context) => {
    const { page, search } = context.query;

    const data = await store.dispatch(
      getCharacters.initiate({
        page: Array.isArray(page) ? page[0] : page ? page : '1',
        searchParams: Array.isArray(search) ? search[0] : search ? search : '',
      })
    );
    await Promise.all(store.dispatch(reduxApi.util.getRunningQueriesThunk()));

    return {
      props: {
        cards: data,
      },
    };
  }
);
