// import { getCharacters } from '@/api/getItems';
import React from 'react';

import { ResponseInfoType } from '@/api/getItems';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Main from '@/components/Main';
import { setPage } from '@/store/reducers/queryParams';
import { useAppDispatch } from '@/store/store';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { useRouter } from 'next/router';

type LayoutPropsType = {
  children?: React.ReactNode;
  data: ResponseInfoType;
};
const ErrorButton = dynamic(() => import('@/components/ErrorButton'), {
  ssr: false,
});

export default function Layout({ data, children }: LayoutPropsType) {
  console.log(data);
  // const [searchParams, setSearchParams] = useSearchParams();
  const dispatch = useAppDispatch();
  const router = useRouter();
  const { search } = router.query;

  const onPageChanged = (page: number) => {
    dispatch(setPage(page.toString()));
    router.push({
      query: {
        page,
        search,
      },
    });
  };

  return (
    <>
      <Head>
        <title>Harry Potter Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href="/favicon.ico" />
      </Head>
      <div className="app">
        <Header />
        <div role="homePage" className="main-container">
          <Main
            className={!children ? 'fullWidth' : 'width2_3'}
            items={data.data}
            count={data.meta.pagination.records}
            onPageChanged={onPageChanged}
          />
          {children}
        </div>
        <ErrorButton />

        <Footer />
      </div>
    </>
  );
}
