import React from 'react';
import type { Metadata } from 'next';
import '@/styles/index.css';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Providers from './providers';

export const metadata: Metadata = {
  title: 'Harry Potter Characters',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="app">
            <Header />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
