// import { Metadata } from 'next';
// import ErrorBoundary from '@/components/ErrorBoundary';
// import { ToastProvider } from '@/components/ToastContext';
// import ThemeContextProvider from '@/context/ThemeContext';
// import Providers from './providers'; // Этот файл создадим дальше
// import '@/styles/index.css';

// export const metadata: Metadata = {
//   title: 'Harry Potter Characters',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <ErrorBoundary>
//           <ThemeContextProvider>
//             <ToastProvider>
//               <Providers>{children}</Providers>
//             </ToastProvider>
//           </ThemeContextProvider>
//         </ErrorBoundary>
//       </body>
//     </html>
//   );
// }

import React from 'react';
import type { Metadata } from 'next';
import '@/styles/index.css';
// import { Providers } from '@/store/Providers';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Providers from './providers';
// import { Providers } from '@/store/Providers';

export const metadata: Metadata = {
  title: 'Harry Potter Characters',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="app">
            <Header />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
